name: flutter_hotel_booking
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1

  # Meta
  meta: ^1.16.0

  # State Management
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  provider: ^6.1.5+1

  # Dependency Injection
  get_it: ^8.2.0

  # Navigation
  go_router: ^16.2.4

  # Logging
  logger: ^2.6.1

  # Networking / HTTP
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3

  # URL / External Launch
  url_launcher: ^6.3.2
  share_plus: ^12.0.1

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_remote_config: ^6.1.1
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4

  # Local Notifications
  # flutter_local_notifications: ^19.5.0
  



  gen:
    path: module/gen
  package_info_plus: ^9.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  
  very_good_analysis: ^9.0.0


flutter:

  uses-material-design: true

  


