name: flutter_hotel_booking
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  provider: ^6.1.5+1

  # Dependency Injection
  get_it: ^8.2.0

  # Navigation
  go_router: ^16.2.4

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_remote_config: ^6.1.1
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4

  # Networking
  http: ^1.6.0

  # Local Storage
  shared_preferences: ^2.5.3

  # UI Components
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1
  pinput: ^6.0.0

  # Utilities
  uuid: ^4.5.2
  logger: ^2.6.1
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  meta: ^1.16.0

  # Local Modules
  gen:
    path: module/gen
  common:
    path: module/common  
  widgets:
    path: module/widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true