name: flutter_hotel_booking
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  meta: ^1.16.0
  
  #state management
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0


  #dependency injection
  get_it: ^8.2.0

  #navigation 
  go_router: ^16.2.4

  #logging
  logger: ^2.6.1
  
  #http 
  dio: ^5.9.0

  #local storage
  shared_preferences: ^2.5.3

  #url launcher
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  very_good_analysis: ^9.0.0


flutter:

  uses-material-design: true

  